// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package role

import (
	"time"
)

const TableNameGoal = "goal"

// Goal mapped from table <goal>
type GoalDto struct {
	ID        int       `gorm:"column:id" json:"id"`
	Parent    int       `gorm:"column:parent" json:"parent"`
	Startup   int       `gorm:"column:startup" json:"startup"`
	Role      int       `gorm:"column:role" json:"role"`
	User      int       `gorm:"column:user" json:"user"`
	Title     string    `gorm:"column:title" json:"title"`
	Status    string    `gorm:"column:status" json:"status"`
	Created   time.Time `gorm:"column:created" json:"created"`
	Modified  time.Time `gorm:"column:modified" json:"modified"`
	Activated time.Time `gorm:"column:activated" json:"activated"`
	Reached   time.Time `gorm:"column:reached" json:"reached"`
	Approved  time.Time `gorm:"column:approved" json:"approved"`
	Blocked   time.Time `gorm:"column:blocked" json:"blocked"`
	Hidden    time.Time `gorm:"column:hidden" json:"hidden"`
	Notified  int       `gorm:"column:notified" json:"notified"`
}

// TableName Goal's table name
func (*GoalDto) TableName() string {
	return TableNameGoal
}
