// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package role

import (
	"time"
)

const TableNameRoleSkill = "role_skill"

// RoleSkill mapped from table <role_skill>
type RoleSkillDto struct {
	Role      int       `gorm:"column:role" json:"role"`
	Skill     int       `gorm:"column:skill" json:"skill"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName RoleSkill's table name
func (*RoleSkillDto) TableName() string {
	return TableNameRoleSkill
}
