// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package protocol

const TableNameProtocol = "protocol"

// Protocol mapped from table <protocol>
type ProtocolDto struct {
	ID    int        `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string     `gorm:"column:name" json:"name"`
	Tasks []*TaskDto `gorm:"foreignkey:protocol_id"`
}

// TableName Protocol's table name
func (*ProtocolDto) TableName() string {
	return TableNameProtocol
}
