// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

const TableNameIndustry = "industry"

// Industry mapped from table <industry>
type IndustryDto struct {
	ID   int    `gorm:"column:id" json:"id"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName Industry's table name
func (*IndustryDto) TableName() string {
	return TableNameIndustry
}
