// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

const TableNameStartupIndustry = "startup_industry"

// StartupIndustry mapped from table <startup_industry>
type StartupIndustryDto struct {
	Startup  int `gorm:"column:startup" json:"startup"`
	Industry int `gorm:"column:industry" json:"industry"`
	Main     int `gorm:"column:main" json:"main"`
}

// TableName StartupIndustry's table name
func (*StartupIndustryDto) TableName() string {
	return TableNameStartupIndustry
}
