// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

import (
	"time"
)

const TableNameStartup = "startup"

// Startup mapped from table <startup>
type StartupDto struct {
	ID                int       `gorm:"column:id" json:"id"`
	User              int       `gorm:"column:user" json:"user"`
	UserTitle         string    `gorm:"column:user_title" json:"user_title"`
	UserDescription   string    `gorm:"column:user_description" json:"user_description"`
	UserEquity        float64   `gorm:"column:user_equity" json:"user_equity"`
	Name              string    `gorm:"column:name" json:"name"`
	Title             string    `gorm:"column:title" json:"title"`
	Description       string    `gorm:"column:description" json:"description"`
	Avatar            string    `gorm:"column:avatar" json:"avatar"`
	AvatarMd          string    `gorm:"column:avatar_md" json:"avatar_md"`
	Logo              string    `gorm:"column:logo" json:"logo"`
	Icon              string    `gorm:"column:icon" json:"icon"`
	Cover             string    `gorm:"column:cover" json:"cover"`
	CoverMd           string    `gorm:"column:cover_md" json:"cover_md"`
	Video             string    `gorm:"column:video" json:"video"`
	Video720URL       string    `gorm:"column:video_720_url" json:"video_720_url"`
	Video720Job       string    `gorm:"column:video_720_job" json:"video_720_job"`
	Pitch             string    `gorm:"column:pitch" json:"pitch"`
	EquityMin         float64   `gorm:"column:equity_min" json:"equity_min"`
	EquityTotal       float64   `gorm:"column:equity_total" json:"equity_total"`
	Deadline          int       `gorm:"column:deadline" json:"deadline"`
	Vanity            string    `gorm:"column:vanity" json:"vanity"`
	CompanyType       string    `gorm:"column:company_type" json:"company_type"`
	CompanyState      string    `gorm:"column:company_state" json:"company_state"`
	Followers         int       `gorm:"column:followers" json:"followers"`
	Applicants        int       `gorm:"column:applicants" json:"applicants"`
	Views             int       `gorm:"column:views" json:"views"`
	Reports           int       `gorm:"column:reports" json:"reports"`
	Status            string    `gorm:"column:status" json:"status"`
	Created           time.Time `gorm:"column:created" json:"created"`
	Modified          time.Time `gorm:"column:modified" json:"modified"`
	Submitted         time.Time `gorm:"column:submitted" json:"submitted"`
	Reviewed          time.Time `gorm:"column:reviewed" json:"reviewed"`
	Signed            time.Time `gorm:"column:signed" json:"signed"`
	Published         time.Time `gorm:"column:published" json:"published"`
	Development       time.Time `gorm:"column:development" json:"development"`
	Finished          time.Time `gorm:"column:finished" json:"finished"`
	Launched          time.Time `gorm:"column:launched" json:"launched"`
	AwardUploaded     time.Time `gorm:"column:award_uploaded" json:"award_uploaded"`
	Unpublished       time.Time `gorm:"column:unpublished" json:"unpublished"`
	Hidden            time.Time `gorm:"column:hidden" json:"hidden"`
	Blocked           time.Time `gorm:"column:blocked" json:"blocked"`
	Privacy           string    `gorm:"column:privacy" json:"privacy"`
	Confidential      int       `gorm:"column:confidential" json:"confidential"`
	Featured          int       `gorm:"column:featured" json:"featured"`
	Notified          int       `gorm:"column:notified" json:"notified"`
	AddressLine1      string    `gorm:"column:address_line_1" json:"address_line_1"`
	AddressLine2      string    `gorm:"column:address_line_2" json:"address_line_2"`
	AddressLine3      string    `gorm:"column:address_line_3" json:"address_line_3"`
	City              string    `gorm:"column:city" json:"city"`
	State             string    `gorm:"column:state" json:"state"`
	Zipcode           string    `gorm:"column:zipcode" json:"zipcode"`
	Country           string    `gorm:"column:country" json:"country"`
	Email             string    `gorm:"column:email" json:"email"`
	Attn              string    `gorm:"column:attn" json:"attn"`
	SignatureRequest  string    `gorm:"column:signature_request" json:"signature_request"`
	SignatureID       string    `gorm:"column:signature_id" json:"signature_id"`
	AgreementFile     string    `gorm:"column:agreement_file" json:"agreement_file"`
	IncorporationFile string    `gorm:"column:incorporation_file" json:"incorporation_file"`
	EquityAwardFile   string    `gorm:"column:equity_award_file" json:"equity_award_file"`
	Protocol          int       `gorm:"column:protocol;not null" json:"protocol"`
	Topics            []*Topic  `gorm:"many2many:startup_topic;ForeignKey:id;References:id;JoinForeignKey:startup;JoinReferences:topic"`
}

// TableName Startup's table name
func (*StartupDto) TableName() string {
	return TableNameStartup
}
