// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

const TableNameStartupLocation = "startup_location"

// StartupLocation mapped from table <startup_location>
type StartupLocationDto struct {
	ID        int     `gorm:"column:id" json:"id"`
	Startup   int     `gorm:"column:startup" json:"startup"`
	Name      string  `gorm:"column:name" json:"name"`
	Latitude  float64 `gorm:"column:latitude" json:"latitude"`
	Longitude float64 `gorm:"column:longitude" json:"longitude"`
	Main      int     `gorm:"column:main" json:"main"`
}

// TableName StartupLocation's table name
func (*StartupLocationDto) TableName() string {
	return TableNameStartupLocation
}
