// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

import (
	"time"
)

const TableNameStartupMember = "startup_member"

// StartupMember mapped from table <startup_member>
type StartupMemberDto struct {
	ID             int       `gorm:"column:id" json:"id"`
	Startup        int       `gorm:"column:startup" json:"startup"`
	Email          string    `gorm:"column:email" json:"email"`
	User           int       `gorm:"column:user" json:"user"`
	Name           string    `gorm:"column:name" json:"name"`
	Title          string    `gorm:"column:title" json:"title"`
	Description    string    `gorm:"column:description" json:"description"`
	Equity         int       `gorm:"column:equity" json:"equity"`
	Partner        int       `gorm:"column:partner" json:"partner"`
	Status         string    `gorm:"column:status" json:"status"`
	Created        time.Time `gorm:"column:created" json:"created"`
	Invited        time.Time `gorm:"column:invited" json:"invited"`
	Joined         time.Time `gorm:"column:joined" json:"joined"`
	Declined       time.Time `gorm:"column:declined" json:"declined"`
	Blocked        time.Time `gorm:"column:blocked" json:"blocked"`
	Admin          int       `gorm:"column:admin" json:"admin"`
	Recruiter      int       `gorm:"column:recruiter" json:"recruiter"`
	Broadcaster    int       `gorm:"column:broadcaster" json:"broadcaster"`
	Notified       int       `gorm:"column:notified" json:"notified"`
	InvitationHash string    `gorm:"column:invitation_hash" json:"invitation_hash"`
}

// TableName StartupMember's table name
func (*StartupMemberDto) TableName() string {
	return TableNameStartupMember
}
