// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

import (
	"time"
)

const TableNameStartupWebsite = "startup_website"

// StartupWebsite mapped from table <startup_website>
type StartupWebsiteDto struct {
	ID       int       `gorm:"column:id" json:"id"`
	Startup  int       `gorm:"column:startup" json:"startup"`
	URL      string    `gorm:"column:url" json:"url"`
	Date     time.Time `gorm:"column:date" json:"date"`
	Verified int       `gorm:"column:verified" json:"verified"`
	Main     int       `gorm:"column:main" json:"main"`
}

// TableName StartupWebsite's table name
func (*StartupWebsiteDto) TableName() string {
	return TableNameStartupWebsite
}
