// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package startup

const TableNameTopic = "topic"

// Topic mapped from table <topic>
type Topic struct {
	ID       int    `gorm:"column:id" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	Industry int    `gorm:"column:industry" json:"industry"`
	Interest int    `gorm:"column:interest" json:"interest"`
	Skill    int    `gorm:"column:skill" json:"skill"`
	Featured int    `gorm:"column:featured" json:"featured"`
}

// TableName Topic's table name
func (*Topic) TableName() string {
	return TableNameTopic
}
